version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/ruby/Dockerfile
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/src
    depends_on:
      - db
  db:
    build: ./dockerfiles/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
