version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/ruby/Dockerfile
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/src
    depends_on:
      - db
  db:
    build: ./dockerfiles/psql
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
